AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  slackapp_question

  Sample SAM Template for slackapp_question

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  SlackAppQuestionFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: question/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - Statement:
          - Sid: PutItemToDDB
            Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource: !GetAtt QuestionTable.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref QuestionTable
      Events:
        SlackAppQuestionGet:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /question
            Method: get
        SlackAppQuestionPost:
          Type: Api 
          Properties:
            Path: /question
            Method: post
  QuestionTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: trigger_id
        Type: String


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SlackAppQuestionApi:
    Description: "API Gateway endpoint URL for Prod stage for SlackAppQuestion function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/question/"
  SlackAppQuestionFunction:
    Description: "SlackAppQuestionFunction.Arn"
    Value: !GetAtt SlackAppQuestionFunction.Arn
  SlackAppQuestionFunctionRole:
    Description: "Implicit IAM Role created for SlackAppQuestion function"
    Value: !GetAtt SlackAppQuestionFunctionRole.Arn
  TableName:
    Description: "ARN of table"
    Value: !GetAtt QuestionTable.Arn
